### ISSUE TITLE
Bottlerocket is installed on the machine

### ISSUE THREAD

**Issue by webern** [bottlerocket-os/bottlerocket-project-website#111]
**Path to page with conent (_do not_ include domain name):**

landing page.

**What content is incorrect?**

This is correct but could be slightly confusing: "Bottlerocket is installed on the machine or instance where your containers themselves are running."

Perhaps it's obvious that Bottlerocket *is the operating system* of that machine. But perhaps it should say...

**What should the content say or communicate?**

"Bottlerocket is installed as the operating system for the machines that will host your containers."

Or something like that.

**Comment by stockholmux** [comment]
@webern so it's confusing that the sentence doesn't state that Bottlerocket is an operating system?

The first sentence of the paragraph states "Bottlerocket is a Linux-based operating system optimized for hosting containers." When I sub-in your proposed sentence it seems repetitive. (restating "operating system" then followed by "host" ... "containers")

TBH, I'm not happy with the original sentence now that you point it out. The goal for this sentence is to address the common misunderstanding that Bottlerocket installs as the base image in a container. Sadly, I'm not clear that "hosting" containers is universally understood, so the sentence was attempting to rephrasing the idea. But it is an inelegant sentence, for sure. 

Now I'm a bit stuck trying to come up with elegant language that doesn't mirror terms and structure of the first sentence.
