### ISSUE TITLE
The API Unix domain socket is accessible by mounting; 

### ISSUE THREAD

**Issue by bryantbiggs** [bottlerocket-os/bottlerocket-project-website#199]
**Path to page with content (_do not_ include domain name):**
https://github.com/bottlerocket-os/bottlerocket-project-website/blob/73efa01d143f5325b62077dba291cb56c2892eec/content/en/os/1.14.x/concepts/api-driven/index.markdown?plain=1#L17C54-L17C54

**What content is incorrect?**
I'm not positive, but it seems like a path might have been missed after "mounting" - such as `The API Unix domain socket is accessible by mounting /var/lib/bottlerocket.sock;` (clearly I made this up, I have no idea what it actually is 😅)

**What should the content say or communicate?**
Not sure - maybe its intentionally left vague or maybe the path is just missing from the docs

**Comment by bryantbiggs** [comment]
ah, maybe `/run/api.sock`? https://github.com/bottlerocket-os/bottlerocket/blob/24fa6011f4b55b323bc5de3810d77a6188bca4d2/sources/constants/src/lib.rs#L6

**Comment by bryantbiggs** [comment]
FYI - tracking some of these [here](https://github.com/bottlerocket-os/bottlerocket-project-website/compare/main...bryantbiggs:fix/updates?expand=1) while reading through the docs. Love the new docs! Will open a draft PR after finishing the read to discuss any changes that may be off base

**Comment by stockholmux** [comment]
Hey @bryantbiggs! Thanks for the feedback. 

What you called out was intentionally left without a specific path. The idea behind anything in `/concepts` is that it would only have the ideas behind bottlerocket, without getting bogged down in the details.

Let me turn this around on you: is having the path important to you when reading this? I'm very open minded in finding a way to document this either here or elsewhere in the docs.

**Comment by bryantbiggs** [comment]
ah ok, apologies for the confusion. To be fair, this wasn't a detail I was seeking out; more of a question that came up while reading (i.e. - was there meant to be path here). Thanks for the clarification!
