### ISSUE TITLE
Homepage diagrams have hardcoded versions

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket-project-website#200]
**Path to the page with the problem (_do not_ include domain name):** `/`

**Describe the problem:** The homepage has diagrams reference older versions of bottlerocket. It would look better if this was able to be easily updated.

**Screenshot, if possible** 

![Screenshot 2023-07-26 at 7 49 07 AM](https://github.com/bottlerocket-os/bottlerocket-project-website/assets/1152927/9b40add9-c9d7-4949-b8d3-19dfe0d45918)

**Describe how the site should look?**

They should be more recent versions

**Comment by stmcginnis** [comment]
While updating - would be good to use the correct casing for VMware (small "w").

**Comment by stockholmux** [comment]
@stmcginnis Good call. I'll make that change.
