### ISSUE TITLE
Inaccurate description for admin container

### ISSUE THREAD

**Issue by arnaldo2792** [bottlerocket-os/bottlerocket-project-website#263]
**Path to page with content (_do not_ include domain name):**
https://bottlerocket.dev/en/os/1.14.x/concepts/shell-less-host/

**What content is incorrect?**
Admin container do have write access to the “mutable” directories of the host's file system, e.g., I can do this from the admin container:

```bash
[root@admin]# touch /.bottlerocket/rootfs/var/log/touched
[root@admin]# sta
start_admin.sh  stat
[root@admin]# stat /.bottlerocket/rootfs/var/log/touched
  File: '/.bottlerocket/rootfs/var/log/touched'
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 10310h/66320d   Inode: 15878       Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2023-09-07 23:06:23.438799141 +0000
Modify: 2023-09-07 23:06:23.438799141 +0000
Change: 2023-09-07 23:06:23.438799141 +0000
 Birth: -
```

**What should the content say or communicate?**
The content should communicate that the admin container can write to the mutable directories of the host's file system (`/etc`, `/var`).

**Comment by stockholmux** [comment]
@arnaldo2792 Thanks! Is `/etc` and `/var` the extent of the mutable directories in the host fs? Can you provide a link to where this is defined in the `bottlerocket-os/bottlerocket` repo (as a footnote reference for readers).

**Comment by arnaldo2792** [comment]
The only document that explains parts of the filesystem layout of Bottlerocket is [this], it explains that `etc` is a `tmpfs` filesystem (hence mutable), and that the secondary filesystem for local storage is mounted at `/local`, with bind mounts to `/var` and `/opt`.

[this]: https://github.com/bottlerocket-os/bottlerocket/blob/develop/SECURITY_FEATURES.md#stateless-tmpfs-for-etc
