### ISSUE TITLE
Document package differences between variants

### ISSUE THREAD

**Issue by rpkelly** [bottlerocket-os/bottlerocket-project-website#36]
**What I'd like:**
In a [discussion](https://github.com/bottlerocket-os/bottlerocket/discussions/2809) it was brought up that is is not documented that Bottlerocket baremetal variants do not contain the `aws-iam-authenticator` package. I'd like to see documentation detailing the differences between the packages and features available in each variant.

**Any alternatives you've considered:**
Add what variant each package is in to the documentation created for #14

**Comment by stockholmux** [comment]
This is a really good idea, although I think we have to tackle #14 first.
