### ISSUE TITLE
`apiclient` example commands with list value fail

### ISSUE THREAD

**Issue by ginglis13** [bottlerocket-os/bottlerocket-project-website#447]
**Path to page with content (_do not_ include domain name):** /en/os/1.19.x/api/settings/dns/

**What content is incorrect?**

Some `apiclient` commands for modifying settings do not work as is. I've observed this for setting DNS settings. It may be affecting more, though, given commonality is both of the intended values are lists:

```
[ssm-user@control]$ apiclient set settings.dns.search-list=["foo.bar", "baz.foo"]
Unknown argument 'baz.foo]'
[ssm-user@control]$ apiclient set settings.dns.name-servers=["1.2.3.4", "5.6.7.8"]
Unknown argument '5.6.7.8]'
[ssm-user@control]$ apiclient set settings.dns.name-servers=["1.2.3.4"]
Unable to match your input to the data model.  We may not have enough type information.  Please try the --json input form.  Cause: Error deserializing scalar value: invalid type: string "[1.2.3.4]", expected asequence at line 1 column 11
```

Setting these settings with `--json` and respective JSON values works fine.

**What should the content say or communicate?**
The content should either specify these example commands with `--json` and example JSON; or, if these commands can indeed accept toml-like input (which I wasn't able to do), then the input should be corrected.

**Comment by ginglis13** [comment]
I checked other settings where values are a list type where this is also present:

* https://bottlerocket.dev/en/os/1.19.x/api/settings/ntp/
* https://bottlerocket.dev/en/os/1.19.x/api/settings/kubernetes/#allowed-unsafe-sysctls
* https://bottlerocket.dev/en/os/1.19.x/api/settings/kubernetes/#cluster-dns-ip
* https://bottlerocket.dev/en/os/1.19.x/api/settings/kubernetes/#cpu-manager-policy-options
* https://bottlerocket.dev/en/os/1.19.x/api/settings/kubernetes/#node-taints
* https://bottlerocket.dev/en/os/1.19.x/api/settings/network/#no-proxy

**Comment by ginglis13** [comment]
> That is because what looks like TOML is parsed the same as any other command line: The shell is performing word splitting and strips the quotes, thereby creating multiple arguments out of one intended

Yes 😄 

> A way to prevent this is to surround the TOML with single quotes, which prevents expansions, word splitting, and retains literal double quotes for strings.

This was my first instinct, but unfortunately it does not work for lists/sequences (sorry I could have included this in the original issue description):

```
[root@admin]# apiclient set 'settings.dns.name-servers=[1.2.3.4]'
Unable to match your input to the data model.  We may not have enough type information.  Please try the --json input form.  Cause: Error deserializing scalar value: invalid type: string "[1.2.3.4]", expected a sequence at line 1 column 11
[root@admin]# apiclient set 'settings.dns.name-servers=["1.2.3.4"]'
Unable to match your input to the data model.  We may not have enough type information.  Please try the --json input form.  Cause: Error deserializing scalar value: invalid type: string "[\"1.2.3.4\"]", expected a sequence at line 1 column 15
[root@admin]# apiclient set 'settings.dns.name-servers=\["1.2.3.4"\]'
Unable to match your input to the data model.  We may not have enough type information.  Please try the --json input form.  Cause: Error deserializing scalar value: invalid type: string "\\[\"1.2.3.4\"\\]", expected a sequence at line 1 column 19
[root@admin]# apiclient set 'settings.dns.name-servers=\[1.2.3.4\]'
Unable to match your input to the data model.  We may not have enough type information.  Please try the --json input form.  Cause: Error deserializing scalar value: invalid type: string "\\[1.2.3.4\\]", expected a sequence at line 1 column 15
[root@admin]# apiclient set 'settings.dns.name-servers=[1.2.3.4, 4.5.6]'
Unable to match your input to the data model.  We may not have enough type information.  Please try the --json input form.  Cause: Error deserializing scalar value: invalid type: string "[1.2.3.4, 4.5.6]", expected a sequence at line 1 column 18
```

**Comment by stockholmux** [comment]
Yeah, great catch @ginglis13!

I'd love to have an automated workflow to check all these examples, but that would be...uh... complicated.

**Comment by stockholmux** [comment]
@ginglis13 and @markusboehme :

So, I could use your feedback. 

The settings DSL allows for adding literal examples with `direct_toml` and `direct_shell`. 
This would be, by far, the shortest route to fixing this.
So for `settings.ntp.time-servers` I could replace the existing example with this:

```toml
[[docs.ref.time-servers.example]]
direct_toml = """
[settings.ntp]
time-servers = ["169.254.169.123", "time.aws.com"]
"""
direct_shell = """
apiclient set --json '{ "ntp" : { "time-servers" : ["169.254.169.123", "time.aws.com" ] } }'
"""
```

This a no-template change, but it is, IMHO, clunky. And if someone contributes a change they have to _know_ to do this.

Currently, list values are brought in as[ string representation of toml](https://github.com/bottlerocket-os/bottlerocket-project-website/blob/main/data/settings/1.19.x/ntp.toml#L6C1-L7C50), which also feels a little hacky. Example:

```toml
[[docs.ref.time-servers.example]]
value = "[\"169.254.169.123\", \"time.aws.com\"]"
````

It's probably possible to do something where list values are explicitly stored as lists then rendered automatically:

```toml
[[docs.ref.time-servers.example.list]]
value = "169.254.169.123"

[[docs.ref.time-servers.example.list]]
value = "time.aws.com"
```

And it would handle creating the TOML and apiclient --json automatically. It would be a rather larger change from both the data and template side.

WDYT?

**Comment by markusboehme** [comment]
@ginglis13 Sorry, I hadn't actually checked the examples end-to-end and just saw that shell interpretation rules would for sure be causing problems. I wonder if, given the type information of the API model, `apiclient set` could still infer the correct interpretation of e.g. list values. (Of course this would still not fix the documentation for any releases prior to a change like that.)

@stockholmux There's another option that would let us reuse the TOML. It might be nice if the template could determine if that different way is needed though (i.e. when values of non-primitive types are being set). For example,

```bash
apiclient apply <<EOF
[settings.ntp]
time-servers = ["169.254.169.123", "time.aws.com"]
EOF
```

**Comment by stockholmux** [comment]
@markusboehme humm. Heredoc could be a good option. 

The templating system in Hugo (based on go templates) isn't incredibly good at detecting types, but I suppose I could do something like:

```true
[[docs.ref.time-servers.example]]
value = "[\"169.254.169.123\", \"time.aws.com\"]"
heredoc_apiclient = true
```

That would be a small change to the data files and a medium-ish template change.

**Comment by markusboehme** [comment]
If the templates can detect the presence of e.g. square brackets, that might be good enough to find compound TOML values already.

**Comment by stockholmux** [comment]
@markusboehme It's a good thought. I probably could implement this but I'm unsure if it would turn into an eldritch horror inside a template.

**Comment by stockholmux** [comment]
@markusboehme I take it all back, this was pretty easy not a crime against coding at all!
