### ISSUE TITLE
Collapse single entry section pages but retain URL

### ISSUE THREAD

**Issue by stockholmux** [bottlerocket-os/bottlerocket-project-website#85]
There are a number of section pages that have a single entry.

Example `en/os/1.13.x/install/`:
![Screenshot 2023-03-31 at 8 40 54 AM](https://user-images.githubusercontent.com/1152927/229152006-0413c7d4-58de-4c36-bfe3-bd2832bf4978.png)

These pages are kind of useless until there are multiple sections.

Additionally, it adds needless depth to the sidebar nav:

![Screenshot 2023-03-31 at 8 42 23 AM](https://user-images.githubusercontent.com/1152927/229152352-d0facf82-4d83-44a0-826a-71cc47a124c6.png)

I'd like to find a solution that would allow us to eliminate this depth and extraneous section pages while retaining the URL structure for future expansion.

The Install sidebar should have only three children: Amazon ECS, Amazon EKS, and Host Containers, but they should stay at the same URLs (e.g. `/en/os/1.13.x/install/quickstart/aws/ecs/`). This would allow us to add at a later date `/en/os/13.x/install/manual-install/vwmare` while not messing up existing links/urls.

**Comment by mchaker** [comment]
This was discussed and it's best kept open as an issue for now.

There was a potential solution identified that involved "forking" docsy's template for the sidebar, and manually filtering pages with a `navhidden` or `sidebarhidden` parameter set to `true`.

However, that would mean we would have to maintain that "forked" docsy template, and that would be a lot of toil to keep up-to-date if docsy pushes a huge update that we want to adopt.

Given that, it was determined that it's better to keep this issue open than go with the "fork the docsy template" solution.
